import os
import httpx
from app.config import settings

BASE = "https://api.github.com"
SSL_VERIFY = os.getenv("SSL_VERIFY", "true").lower() != "false"


def _headers() -> dict:
    h = {"Accept": "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28"}
    if settings.github_token:
        h["Authorization"] = f"Bearer {settings.github_token}"
    return h


async def get_repo(owner: str, repo: str) -> dict:
    async with httpx.AsyncClient(verify=SSL_VERIFY) as client:
        r = await client.get(f"{BASE}/repos/{owner}/{repo}", headers=_headers(), timeout=15)
        r.raise_for_status()
        return r.json()


async def get_commits(owner: str, repo: str, per_page: int = 30) -> list[dict]:
    async with httpx.AsyncClient(verify=SSL_VERIFY) as client:
        r = await client.get(
            f"{BASE}/repos/{owner}/{repo}/commits",
            headers=_headers(),
            params={"per_page": per_page},
            timeout=15,
        )
        r.raise_for_status()
        return r.json()


async def get_languages(owner: str, repo: str) -> dict:
    async with httpx.AsyncClient(verify=SSL_VERIFY) as client:
        r = await client.get(f"{BASE}/repos/{owner}/{repo}/languages", headers=_headers(), timeout=15)
        r.raise_for_status()
        return r.json()


async def get_contributors(owner: str, repo: str) -> list[dict]:
    async with httpx.AsyncClient(verify=SSL_VERIFY) as client:
        r = await client.get(
            f"{BASE}/repos/{owner}/{repo}/contributors",
            headers=_headers(),
            params={"per_page": 10},
            timeout=15,
        )
        r.raise_for_status()
        return r.json()


async def get_file_content(owner: str, repo: str, path: str) -> tuple[str, str]:
    """Returns (decoded_text, blob_sha) for the file at path."""
    import base64
    async with httpx.AsyncClient(verify=SSL_VERIFY) as client:
        r = await client.get(f"{BASE}/repos/{owner}/{repo}/contents/{path}",
                             headers=_headers(), timeout=15)
        r.raise_for_status()
        data = r.json()
        text = base64.b64decode(data["content"].replace("\n", "")).decode("utf-8", errors="replace")
        return text, data["sha"]


async def create_fix_pr(owner: str, repo: str, issue_key: str, issue_message: str,
                        file_path: str, fixed_content: str, file_sha: str, analysis: str) -> dict:
    """Create a branch, commit the fixed file content, and open a PR."""
    import base64
    import time

    slug = issue_key.replace(":", "-")[:40]
    branch = f"sonar-fix/{slug}-{int(time.time())}"

    async with httpx.AsyncClient(verify=SSL_VERIFY) as client:
        h = _headers()

        # Get default branch + HEAD SHA
        repo_data = (await client.get(f"{BASE}/repos/{owner}/{repo}", headers=h, timeout=15)).json()
        default_branch = repo_data.get("default_branch", "main")
        ref_data = (await client.get(f"{BASE}/repos/{owner}/{repo}/git/ref/heads/{default_branch}", headers=h, timeout=15)).json()
        head_sha = ref_data["object"]["sha"]

        # Create branch
        br = await client.post(f"{BASE}/repos/{owner}/{repo}/git/refs", headers=h, timeout=15,
                               json={"ref": f"refs/heads/{branch}", "sha": head_sha})
        br.raise_for_status()

        # Commit the fixed file onto the new branch
        fc = await client.put(
            f"{BASE}/repos/{owner}/{repo}/contents/{file_path}",
            headers=h, timeout=30,
            json={
                "message": f"fix({issue_key}): {issue_message[:60]}",
                "content": base64.b64encode(fixed_content.encode()).decode(),
                "sha": file_sha,
                "branch": branch,
            },
        )
        fc.raise_for_status()

        # Open PR
        pr = await client.post(f"{BASE}/repos/{owner}/{repo}/pulls", headers=h, timeout=15, json={
            "title": f"fix: {issue_message[:72]}",
            "body": (
                f"## SonarQube Issue\n\n"
                f"**Key:** `{issue_key}`  \n**File:** `{file_path}`\n\n"
                f"## AI Analysis & Fix\n\n{analysis}\n\n"
                f"---\n*Generated by TechDebt AI*"
            ),
            "head": branch,
            "base": default_branch,
        })
        pr.raise_for_status()
        return pr.json()


async def get_file_churn(owner: str, repo: str, file_paths: list[str], per_file_limit: int = 100) -> dict[str, int]:
    """Return commit count per file path (churn metric)."""
    import asyncio

    async def _count(path: str) -> tuple[str, int]:
        async with httpx.AsyncClient(verify=SSL_VERIFY) as client:
            r = await client.get(
                f"{BASE}/repos/{owner}/{repo}/commits",
                headers=_headers(),
                params={"path": path, "per_page": per_file_limit},
                timeout=20,
            )
            if r.status_code == 200:
                return path, len(r.json())
            return path, 0

    # Cap concurrency — GitHub rate limits at 5000 req/hr with auth
    results = await asyncio.gather(*[_count(p) for p in file_paths[:50]])
    return {path: count for path, count in results}


async def get_issues_open(owner: str, repo: str) -> list[dict]:
    async with httpx.AsyncClient(verify=SSL_VERIFY) as client:
        r = await client.get(
            f"{BASE}/repos/{owner}/{repo}/issues",
            headers=_headers(),
            params={"state": "open", "per_page": 20},
            timeout=15,
        )
        r.raise_for_status()
        return r.json()
